name: 'dbt-state-demo'
version: '1.0.0'
config-version: 2

model-paths: ["models"]
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

profile: 'dbt-state-demo'

dbt-cloud:
  account-host: "ma441.au1.dbt.com"
  project-id: 20635

models:
  dbt-state-demo:
    staging:
      +materialized: view
    marts:
      +materialized: table
