name: 'analytics'
version: '1.0.0'
config-version: 2

model-paths: ["models"]
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

profile: 'analytics'

dbt-cloud:
  account-host: "ma441.au1.dbt.com"
  project-id: 10582

models:
  analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
